# Generated by Django 4.2.6 on 2023-10-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('last', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, unique=True)),
                ('number', models.IntegerField(max_length=20, verbose_name='Telefon nomer')),
                ('place', models.IntegerField(blank=True, choices=[(1, 'Toshkent'), (2, 'Andijon'), (3, "Farg'ona"), (4, 'Namangan'), (5, 'Sirdaryo'), (6, 'Jizzax'), (7, 'Samarqand'), (8, 'Navoiy'), (9, 'Surxondaryo'), (10, 'Qashqadaryo'), (11, 'Xorazm'), (12, 'Qoraqalpoq')], default=1, null=True)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
            },
        ),
    ]
