# Generated by Django 4.2.6 on 2023-10-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.IntegerField(verbose_name='Telefon nomer'),
        ),
    ]
