# Generated by Django 4.2.6 on 2023-10-05 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('from_app', '0002_alter_customer_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50, verbose_name='Ochilgan yili')),
                ('name', models.CharField(max_length=100, verbose_name='companiya nomi')),
                ('body', models.TextField(verbose_name='Jamoa haqida')),
                ('image', models.ImageField(upload_to='year/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guruh',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomlari')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='f nomi')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('number', models.CharField(max_length=30, verbose_name='f nomeri')),
                ('subject', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'kontack',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot  nomi')),
                ('title', models.TextField(verbose_name='Mahsulot haqida ')),
                ('image', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='from_app.category')),
            ],
            options={
                'verbose_name': 'Mahsulot',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Services nomi')),
                ('title', models.TextField(verbose_name='Services haqida ')),
                ('image', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'serverlar',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='M name')),
                ('job', models.CharField(max_length=200, verbose_name='Kasbi')),
                ('image', models.ImageField(upload_to='team/')),
                ('tw_link', models.URLField(max_length=4000, verbose_name='link')),
                ('fb_link', models.URLField(max_length=4000, verbose_name='link')),
                ('in_link', models.URLField(max_length=4000, verbose_name='link')),
            ],
            options={
                'verbose_name': 'Jamoa',
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
