# Generated by Django 4.2.5 on 2023-12-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from_app', '0003_about_category_contact_product_services_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('link_t', models.URLField()),
                ('link_f', models.URLField()),
                ('link_link', models.URLField()),
            ],
            options={
                'verbose_name': 'Bizning jamoa_',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
